"""M5 风控 RMS：规则引擎、13 条规则、VaR/ES、验收指标。"""

from __future__ import annotations

from .base import (
    DayState,
    EngineState,
    NullRiskEngine,
    RiskContext,
    RiskEngine,
    RiskRule,
    RiskStats,
    RiskTrigger,
)
from .engine import RuleRiskEngine
from .registry import (
    RULE_REGISTRY,
    available_rules,
    build_rule,
    build_rules,
    get_rule_class,
    register_rule,
)
from .rules import (
    CancelRatioRule,
    CashSufficiencyRule,
    DailyLossLimitRule,
    GrossExposureRule,
    IndustryExposureRule,
    MaxDrawdownRule,
    MaxOrderNotionalRule,
    MaxOrderQuantityRule,
    MaxPositionPerSymbolRule,
    MaxTradeVolumeDailyRule,
    OrderFrequencyRule,
    PortfolioVaRLimitRule,
    PriceDeviationRule,
)
from .stats import (
    LatencyReport,
    RejectionRecord,
    RejectionReport,
    evaluate_rejections,
    summarize_latency,
)
from .var import (
    BreachResult,
    VaRResult,
    expected_shortfall,
    historical_var_es,
    portfolio_returns,
    quantile_loss,
    var_breach_rate,
)

__all__ = [
    "DayState",
    "EngineState",
    "NullRiskEngine",
    "RiskContext",
    "RiskEngine",
    "RiskRule",
    "RiskTrigger",
    "RiskStats",
    "RuleRiskEngine",
    "RULE_REGISTRY",
    "available_rules",
    "build_rule",
    "build_rules",
    "get_rule_class",
    "register_rule",
    "CancelRatioRule",
    "CashSufficiencyRule",
    "DailyLossLimitRule",
    "GrossExposureRule",
    "IndustryExposureRule",
    "MaxDrawdownRule",
    "MaxOrderNotionalRule",
    "MaxOrderQuantityRule",
    "MaxPositionPerSymbolRule",
    "MaxTradeVolumeDailyRule",
    "OrderFrequencyRule",
    "PortfolioVaRLimitRule",
    "PriceDeviationRule",
    "LatencyReport",
    "RejectionRecord",
    "RejectionReport",
    "evaluate_rejections",
    "summarize_latency",
    "BreachResult",
    "VaRResult",
    "expected_shortfall",
    "historical_var_es",
    "portfolio_returns",
    "quantile_loss",
    "var_breach_rate",
]
