"""配置层：强类型 schema + YAML 加载/覆盖。"""

from __future__ import annotations

from .loader import (
    PROJECT_ROOT,
    env_overrides,
    load_base_config,
    load_cost_scenario,
    load_risk_config,
    load_strategy_config,
    load_yaml,
    parse_override,
    parse_overrides,
    resolve_path,
)
from .schema import (
    BaseConfig,
    CalendarConfig,
    CostConfig,
    DataConfig,
    EngineConfig,
    ImpactConfig,
    KellyConfig,
    LiquidityConfig,
    MatchingConfig,
    PortfolioConfig,
    PriceLimitConfig,
    ProjectConfig,
    QualityConfig,
    ReportConfig,
    RiskAlertsConfig,
    RiskConfig,
    RiskRefConfig,
    RiskRuleConfig,
    SlippageConfig,
    StampTaxConfig,
    StampTaxRule,
    StrategyRefConfig,
    UniverseConfig,
    construct,
)

__all__ = [
    "PROJECT_ROOT",
    "env_overrides",
    "load_base_config",
    "load_cost_scenario",
    "load_risk_config",
    "load_strategy_config",
    "load_yaml",
    "parse_override",
    "parse_overrides",
    "resolve_path",
    "BaseConfig",
    "CalendarConfig",
    "CostConfig",
    "DataConfig",
    "EngineConfig",
    "ImpactConfig",
    "KellyConfig",
    "LiquidityConfig",
    "MatchingConfig",
    "PortfolioConfig",
    "PriceLimitConfig",
    "ProjectConfig",
    "QualityConfig",
    "ReportConfig",
    "RiskAlertsConfig",
    "RiskConfig",
    "RiskRefConfig",
    "RiskRuleConfig",
    "SlippageConfig",
    "StampTaxConfig",
    "StampTaxRule",
    "StrategyRefConfig",
    "UniverseConfig",
    "construct",
]
