"""M0 基础设施：枚举、数据模型、事件、日历、异常、日志。"""

from __future__ import annotations

from .calendar import TradingCalendar
from .dates import DateLike, phase_timestamp, to_date, to_timestamp
from .enums import (
    Board,
    EventType,
    FillSource,
    OrderStatus,
    OrderType,
    RejectReason,
    RiskAction,
    SessionPhase,
    Side,
    SignalDirection,
    TimeInForce,
    TradingStatus,
)
from .events import (
    Event,
    EventLoop,
    EventQueue,
    EventRecord,
    EventRecorder,
    FillEvent,
    LoopStats,
    MarketDataEvent,
    OrderEvent,
    RiskCheckEvent,
    SignalEvent,
    TimerEvent,
)
from .exceptions import (
    AQSError,
    ConfigError,
    DataError,
    DataQualityError,
    EngineError,
    FutureFunctionError,
    InsufficientDataError,
    LookaheadError,
    OrderRejectedError,
    RiskError,
    SchemaError,
)
from .logging import AuditRecord, AuditStream, get_logger, setup_logging
from .models import (
    Bar,
    CostBreakdown,
    Fill,
    MarketSnapshot,
    Order,
    RiskDecision,
    SignalIntent,
    SymbolMeta,
)

__all__ = [
    "TradingCalendar",
    "DateLike",
    "to_date",
    "to_timestamp",
    "phase_timestamp",
    "Board",
    "EventType",
    "FillSource",
    "OrderStatus",
    "OrderType",
    "RejectReason",
    "RiskAction",
    "SessionPhase",
    "Side",
    "SignalDirection",
    "TimeInForce",
    "TradingStatus",
    "Event",
    "EventLoop",
    "EventQueue",
    "EventRecord",
    "EventRecorder",
    "FillEvent",
    "LoopStats",
    "MarketDataEvent",
    "OrderEvent",
    "RiskCheckEvent",
    "SignalEvent",
    "TimerEvent",
    "AQSError",
    "ConfigError",
    "DataError",
    "DataQualityError",
    "EngineError",
    "FutureFunctionError",
    "InsufficientDataError",
    "LookaheadError",
    "OrderRejectedError",
    "RiskError",
    "SchemaError",
    "AuditRecord",
    "AuditStream",
    "get_logger",
    "setup_logging",
    "Bar",
    "CostBreakdown",
    "Fill",
    "MarketSnapshot",
    "Order",
    "RiskDecision",
    "SignalIntent",
    "SymbolMeta",
]
